### ISSUE TITLE
kevent-demo doesn't compile on Linux

### ISSUE THREAD

**Issue by Avamander** [rene0/dcf77pi#38]
The kevent-demo added in https://github.com/rene0/dcf77pi/commit/1c1b5c41dadee5c5341fb8887020d092f58cb517 doesn't compile on linux due to the lack of `sys/event.h`. It would be good to exclude that file when compiling on Linux.

**Comment by rene0** [comment]
Thanks for noticing, I verified that kevent-demo indeed fails to build on Ubuntu 18.04. The underlying problem is that the kevent API is only available on FreeBSD, which my Raspberry Pi runs normally.

The idea of kevent-demo and the "interrupt"  branch is to figure out a cross-platform (at least Linux and FreeBSD) method to get a more precise timing on the pulses than what is currently done using the nanosleep call, which tends to sleep in. At a sample rate of 1000 Hz it looses about 6% of the samples each second. Alternatives to using the kevent API might be to send an signal (SIGALRM) to ourselves each millisecond (or whatever you set hw.freq in config.json to), or probably better using the setitimer call (see https://nativeguru.wordpress.com/2015/02/19/why-you-should-avoid-using-sigalrm-for-timer/ for some nice story).

**Comment by Avamander** [comment]
Is there a reason real interrupts aren't used instead of polling?

**Comment by rene0** [comment]
No, it just started out that way, as something that worked on my Raspberry Pi 1B.

**Comment by Avamander** [comment]
Makes sense. 

Just mentioning that sysfs (`/sys/class/gpio/gpioX/direction` etc.) has been deprecated and some distros already only have chardev, if at some point chardev support was to be added, it might be optimal to see if interrupts could be used?

**Comment by rene0** [comment]
It looks like chardev support is more important for the Linux port, I'll replace the legacy sysfs code with that. The latest Raspbian runs kernel 4.19 which supports both ways of interfacing with GPIO. See issue #39
